name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      gogopool:
        node-version: [14.x, 16.x]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Configure yarn caching
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node.js ${{ gogopool.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ gogopool.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Format the code
        run: yarn run prettier
      - name: Check the code style
        run: yarn run lint:eslint
      - name: Check the types
        run: yarn run check-types
      - name: Build the project
        run: yarn run build
